New Install methods now compatible with other APT

diff --git a/install/inc/functions b/install/inc/functions
--- a/install/inc/functions
+++ b/install/inc/functions
@@ -2,18 +2,53 @@
 # Stolen from : https://github.com/Grafikart/dotfiles
 
 tell() {
-  echo  "\033[0;33m|-- ${*}\033[0m"
-  $* || {
-    echo  "\033[0;31mFail !" 1>&2 ;
-    echo   "\033[0m"
-    exit 1 ;
+  echo "\033[0;33m|-- ${*}\033[0m"
+    $* || {
+    echo "\033[0;31mFail !" 1>&2 ;
+    echo "\033[0m"
+    exit 1;
   }
 }
 
 explain() {
-  echo  "\033[0;34m${1}\033[0m"
+  echo "\033[0;34m${1}\033[0m"
 }
 
 success() {
-  echo  "\033[0;32m${1}\033[0m"
+  echo "\033[0;32m${1}\033[0m"
+}
+
+install_cmd(){
+
+  PACKAGE_NAME=$@
+
+  YUM_CMD=$(which yum)
+  APT_GET_CMD=$(which apt-get)
+  BREW_CMD=$(which brew)
+
+  # add your own package
+
+  #TEMPLATE=$(which template)
+
+  if [ ! -z $YUM_CMD ]; then
+    sudo yum install $PACKAGE_NAME
+
+  elif [ ! -z $APT_GET_CMD ]; then
+    sudo apt-get install $PACKAGE_NAME
+
+  elif [ ! -z $BREW_CMD ]; then
+    sudo brew install $PACKAGE_NAME
+
+  #elif [ ! -z $TEMPLATE ]; then
+    #sudo template install $PACKAGE_NAME
+
+  else
+
+    echo "\033[0;31m" 1>&2 ;
+    echo "Error can't install package $PACKAGE_NAME"
+    echo "\033[0m"
+    echo "No package manager found"
+    echo "please add yours to $HOME/dotfiles/install/inc/functions"
+    exit 1;
+  fi
 }
diff --git a/install/vimplug b/install/vimplug
--- a/install/vimplug
+++ b/install/vimplug
@@ -1,12 +1,30 @@
 #!/bin/sh
 
+BASEDIR=$(dirname $0)
+. $BASEDIR/inc/functions
+
+
+curl --version 2>&1 > /dev/null
+if [ $? -ne 0 ]; then
+  echo "Could not find curl."
+  exit 1
+fi
+
+wget --version 2>&1 > /dev/null
+if [ $? -ne 0 ]; then
+  echo "Could not find wget"
+  exit 1
+fi
+
 if [ ! -e $HOME/.vim/autoload ]; then
+  explain "Download Vim-plug (Vim plugins manager)"
   #git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
   curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
 fi
 
 if [ ! -e $HOME/.vim/spell ]; then
+  explain "Spelling dictionary"
   mkdir -p ~/.vim/spell
   cd ~/.vim/spell
   wget http://ftp.vim.org/vim/runtime/spell/fr.latin1.spl
@@ -18,11 +36,13 @@ if [ ! -e $HOME/.vim/spell ]; then
 fi
 
 if [ ! -e  $HOME/.vim/syntax/ngnix.vim ]; then
+  explain "Nginx syntax"
   # Nginx syntax
   curl -flo ~/.vim/syntax/ngnix.vim --create-dirs \
     https://raw.githubusercontent.com/nginx/nginx/master/contrib/vim/syntax/nginx.vim
 fi
 
+explain "Vim plugins"
 vim -u $HOME/.vimrc.bundles +PlugUpgrade +qa
 vim -u $HOME/.vimrc.bundles +PlugInstall +qa
 vim -u $HOME/.vimrc.bundles +PlugUpdate +qa
